// Post-execution quality passes — run at the end of every execution loop.
//
// 1. ensureProjectScaffolding: EVERY generated project gets the industrial
//    baseline — README.md (overview, stack, structure, setup, governance
//    provenance) and .gitignore — written deterministically from session truth
//    when the routed models didn't already ship them.
// 2. ensurePreviewEntry: EVERY completed project with files gets a runnable
//    index.html so the workspace Preview renders the real app — web targets get
//    a full-page app, mobile targets get a phone-style app screen. If no task
//    produced one, a single bounded model call generates the entry.
//
// Both passes are best-effort: a failure is a Trust Ledger event, never a
// failed execution run.

import type { PipelineSession } from "../schemas/pipeline";
import { recordToLedger } from "./ledger";
import { applyFileOpToSession, type FileOp } from "./workspace";
import { extractFileOps } from "./fileops";
import { geminiAdapters } from "../lib/ai/provider";
import { stackTextOf } from "../lib/pipeline/gates";

const SCAFFOLD_TASK_ID = "scaffolding";
const SCAFFOLD_MODEL = "verya/system";
const PREVIEW_TASK_ID = "preview-entry";

// ---------- 1. Professional scaffolding ----------

export async function ensureProjectScaffolding(orgId: string, session: PipelineSession): Promise<void> {
  const files = session.workspaceFiles ?? [];
  if (files.length === 0) return;
  const paths = new Set(files.map((f) => f.path));
  const created: string[] = [];

  if (!paths.has("README.md")) {
    const op: FileOp = { path: "README.md", operation: "create", content: readmeFor(session) };
    const res = applyFileOpToSession(session, op, { taskId: SCAFFOLD_TASK_ID, model: SCAFFOLD_MODEL });
    if (res.ok) created.push("README.md");
  }

  if (!paths.has(".gitignore")) {
    const op: FileOp = { path: ".gitignore", operation: "create", content: GITIGNORE };
    const res = applyFileOpToSession(session, op, { taskId: SCAFFOLD_TASK_ID, model: SCAFFOLD_MODEL });
    if (res.ok) created.push(".gitignore");
  }

  if (created.length > 0) {
    await recordToLedger({
      orgId,
      sessionId: session.id,
      gate: "execution",
      eventType: "project_scaffolded",
      actor: "system",
      detail: { summary: `Project scaffold added: ${created.join(", ")} (industrial baseline)`, files: created },
    }).catch(() => undefined);
  }
}

function readmeFor(session: PipelineSession): string {
  const title = session.workflow?.title ?? "Generated Project";
  const summary = session.workflow?.summary ?? "";
  const stack = stackTextOf(session).trim();
  const files = (session.workspaceFiles ?? []).map((f) => f.path).sort();
  const tree = treeText(files);
  const routes = session.routing?.routes ?? [];
  const verified = session.executions.filter((e) => e.status === "verified").length;
  const flagged = session.executions.filter((e) => e.status === "flagged").length;
  const failed = session.executions.filter((e) => e.status === "failed").length;

  const modelLines = routes
    .slice(0, 20)
    .map((r) => `| ${r.taskTitle} | \`${r.selectedModel}\` |`)
    .join("\n");

  const runSteps = stack.toLowerCase().includes("node") || stack.toLowerCase().includes("npm")
    ? "1. `npm install`\n2. `npm run dev` (or `npm start`)\n3. Open the printed local URL."
    : stack.toLowerCase().includes("python")
      ? "1. `python -m venv .venv`\n2. `pip install -r requirements.txt`\n3. `python -m src.main` (entry point per module)."
      : "Open `index.html` in a browser (self-contained — no build step).";

  return `# ${title}

${summary ? `> ${summary}\n` : ""}
## Overview

This project was planned, routed, and generated by **Verya** — AI-governed planning,
model routing, verification, and audit-ready proof. Every file below was produced by
the model assigned to its task and recorded in the Trust Ledger.

## Tech Stack

${stack || "See the generated source files."}

## Project Structure

\`\`\`
${tree}
\`\`\`

## Getting Started

${runSteps}

## Quality & Governance

| Signal | Count |
| --- | --- |
| Tasks verified | ${verified} |
| Tasks flagged for review | ${flagged} |
| Tasks failed | ${failed} |
| Routing policy | \`${session.policy ?? "balanced"}\` |

${modelLines ? `### Model assignments\n\n| Task | Model |\n| --- | --- |\n${modelLines}\n` : ""}
## Provenance

- Session: \`${session.id}\`
- Generated: ${new Date().toISOString()}
- Verification and file-level provenance: Verya Trust Ledger.

## License

Add your license here.
`;
}

const GITIGNORE = `# Dependencies
node_modules/
__pycache__/
.venv/
venv/

# Build output
dist/
build/
.next/
out/

# Environment
.env
.env.*
!.env.example

# Logs
*.log
npm-debug.log*

# OS / Editor
.DS_Store
Thumbs.db
.idea/
.vscode/

# Test coverage
coverage/
.pytest_cache/
`;

/** Compact box-drawing tree for README structure sections. */
function treeText(paths: string[]): string {
  type Node = { name: string; children: Map<string, Node> };
  const root: Node = { name: ".", children: new Map() };
  for (const p of paths) {
    let node = root;
    for (const seg of p.split("/")) {
      if (!node.children.has(seg)) node.children.set(seg, { name: seg, children: new Map() });
      node = node.children.get(seg)!;
    }
  }
  const lines: string[] = [];
  const walk = (node: Node, prefix: string) => {
    const entries = [...node.children.values()].sort((a, b) => {
      const aDir = a.children.size > 0, bDir = b.children.size > 0;
      return aDir === bDir ? a.name.localeCompare(b.name) : aDir ? -1 : 1;
    });
    entries.forEach((child, i) => {
      const last = i === entries.length - 1;
      lines.push(`${prefix}${last ? "└── " : "├── "}${child.name}${child.children.size > 0 ? "/" : ""}`);
      if (child.children.size > 0) walk(child, `${prefix}${last ? "    " : "│   "}`);
    });
  };
  walk(root, "");
  return lines.slice(0, 80).join("\n") || "(no files yet)";
}

// ---------- 2. Guaranteed preview entry for web projects ----------

export async function ensurePreviewEntry(orgId: string, session: PipelineSession): Promise<void> {
  const platform = (session.targetPlatform ?? "web").toLowerCase();

  const files = session.workspaceFiles ?? [];
  if (files.length === 0) return;
  if (files.some((f) => f.path.toLowerCase().endsWith(".html"))) return; // already previewable

  const model =
    session.executions.find((e) => e.status === "verified" || e.status === "flagged")?.servedBy ??
    session.executions.find((e) => e.model)?.model ??
    "openai/gpt-oss-20b";

  try {
    const { output, servedBy } = await geminiAdapters.generatePreviewEntry({
      projectTitle: session.workflow?.title ?? "Generated Project",
      summary: session.workflow?.summary ?? "",
      stack: stackTextOf(session),
      platform,
      files: files.slice(0, 40).map((f) => ({
        path: f.path,
        excerpt: f.path.toLowerCase().endsWith(".html") ? f.content.slice(0, 300) : "",
      })),
      model,
    });

    const ops = extractFileOps(output);
    const applied: string[] = [];
    for (const op of ops) {
      // Only entry-page artifacts may be created by this pass.
      if (!/\.(html?|css|js)$/i.test(op.path)) continue;
      const res = applyFileOpToSession(session, op, { taskId: PREVIEW_TASK_ID, model: servedBy ?? model });
      if (res.ok) applied.push(res.op.path);
    }

    await recordToLedger({
      orgId,
      sessionId: session.id,
      gate: "execution",
      eventType: applied.length > 0 ? "preview_entry_generated" : "preview_entry_failed",
      actor: "ai",
      model: servedBy ?? model,
      detail: {
        summary:
          applied.length > 0
            ? `Preview entry generated for the web project: ${applied.join(", ")}`
            : "Preview entry generation produced no usable files — workspace preview falls back to the file inventory.",
        files: applied,
      },
    }).catch(() => undefined);
  } catch (err) {
    await recordToLedger({
      orgId,
      sessionId: session.id,
      gate: "execution",
      eventType: "preview_entry_failed",
      actor: "system",
      detail: {
        summary: `Preview entry generation failed: ${err instanceof Error ? err.message : "unknown error"}`,
      },
    }).catch(() => undefined);
  }
}
